### PR TITLE
Moved binary to examples

### PR DESCRIPTION
**Pull request by expenses**
Personally, I feel like it makes more sense to have your opencv demo in `examples/`.

### CODE REVIEW

**Comment by atomashpolskiy** [comment]
It might be a good idea. Unfortunately, moving `opencv_demo` to examples means that now it's going to be automatically compiled by Cargo. Which is a good thing by itself (and particularly for CI purposes), but effectively requires the host to have an OpenCV installation, even if the user does not intend to run the demo :/

**Comment by atomashpolskiy** [comment]
Maybe it would make sense to get rid of OpenCV completely and use some pure Rust image processing library instead?

**Comment by expenses** [comment]
Ideally you'd use [image](https://crates.io/crates/image), yeah. I'll look into it tomorrow (it's getting late here).

**Comment by expenses** [comment]
I've pushed a new commit that uses the `image` and `imageproc` crates and works quite well. The `draw_hollow_rect_mut` doesn't have a width option which is a shame, but I suppose we could write our own function if that was needed. I also haven't found a good way to display the image, so it just writes to a file for now.

**Comment by atomashpolskiy** [comment]
Nice work! Thank you very much! I merged your changes and updated instructions in the readme

**Pull request merged**
